# Generated by Django 5.2 on 2025-05-08 00:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.TextField()),
                ('alunos', models.ManyToManyField(blank=True, related_name='cursos_matriculados', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(limit_choices_to={'tipo': 'escola'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('professores', models.ManyToManyField(blank=True, related_name='cursos_lecionados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('ordem', models.PositiveIntegerField()),
                ('url', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('aula', 'Aula'), ('exercicio', 'Exercício')], default='aula', max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'ordering': ['curso', 'ordem'],
                'unique_together': {('curso', 'ordem', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.capitulo')),
            ],
            options={
                'unique_together': {('aluno', 'capitulo')},
            },
        ),
    ]
