# Generated by Django 5.2 on 2025-05-08 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_improve_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulo',
            options={'ordering': ['curso', 'ordem', 'tipo'], 'verbose_name': 'Capítulo', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='progresso',
            options={'verbose_name': 'Progresso', 'verbose_name_plural': 'Progressos'},
        ),
    ]
