# Generated by Django 5.2 on 2025-05-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_fix_exercicio_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='ordem',
            field=models.DecimalField(decimal_places=1, help_text='Use valores como 1.0 para aulas e 1.5 para exercícios relacionados', max_digits=5),
        ),
    ]
