# Generated by Django 5.2 on 2025-05-10 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_force_exercise_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='escola',
        ),
        migrations.AddField(
            model_name='curso',
            name='escolas',
            field=models.ManyToManyField(limit_choices_to={'tipo': 'escola'}, related_name='cursos_da_escola', to=settings.AUTH_USER_MODEL),
        ),
    ]
