# Generated by Django 5.2 on 2025-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ativo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_escola',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('escola', 'Escola')], max_length=20),
        ),
    ]
