# Generated by Django 5.2 on 2025-05-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_ativo_usuario_nome_escola_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_escola',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Escola'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('escola', 'Escola'), ('aluno', 'Aluno'), ('professor', 'Professor')], default='aluno', max_length=10),
        ),
    ]
