# Generated by Django 5.2 on 2025-05-09 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_options_alter_usuario_nome_escola_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome_escola',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='escola',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'escola'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
